# Generated by Django 5.2.1 on 2025-05-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='concerns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='review_media/'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='review_description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='Untitled Review', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='skin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='review_uploads/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='product.review')),
            ],
        ),
    ]
