# Generated by Django 5.2.1 on 2025-05-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review_age_review_concerns_review_email_review_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='concerns',
        ),
    ]
