# Generated by Django 5.2.1 on 2025-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_review_concerns'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='concerns',
            field=models.JSONField(blank=True, choices=[('acne', 'Acne'), ('ageing', 'Ageing'), ('pigmentation', 'Pigmentation'), ('redness', 'Redness'), ('sensitivity', 'Sensitivity'), ('scarring', 'Scarring'), ('blackheads', 'Blackheads'), ('oiliness', 'Oiliness'), ('wrinkles', 'Wrinkles'), ('dryness', 'Dryness'), ('large pores', 'Large Pores'), ('sun damage', 'Sun Damage'), ('irritation', 'Irritation'), ('texture', 'Texture')], null=True),
        ),
    ]
