# Generated by Django 5.2.1 on 2025-05-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_review_concerns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
