# Generated by Django 5.2.1 on 2025-05-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_review_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='media',
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='concerns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='file',
            field=models.FileField(upload_to='review_media/'),
        ),
    ]
