export const products = [
  {
    id: 1,
    name: "Hommes",
    category: "Vêtements",
    title: "T-shirt pour Hommes",
    price: 100,
    oldPrice: 130,
    discount: 30,
    reviews: 1200,
    date: "2024-05-01",
    image1: "src/public/images/homme1.jpeg",
    image2: "src/public/images/homme2.jpeg",
  },
  {
    id: 2,
    name: "Montres Connectées",
    category: "Électroniques",
    title: "Montre Connectée Premium",
    price: 200,
    oldPrice: 250,
    discount: 50,
    reviews: 900,
    date: "2020-09-13",
    image1: "src/public/images/watch1.jpeg",
    image2: "src/public/images/watch2.jpeg",
  },
  {
    id: 3,
    name: "Ordinateurs",
    category: "Électroniques",
    title: "Ordinateur Portable",
    price: 300,
    oldPrice: 400,
    discount: 100,
    reviews: 1567,
    date: "2020-07-15",
    image1: "src/public/images/ordi1.jpeg",
    image2: "src/public/images/ordi2.jpeg",
  },
  {
    id: 4,
    name: "Climatiseur",
    category: "Électroménagers",
    title: "Climatiseur Split",
    price: 300,
    oldPrice: 370,
    discount: 70,
    reviews: 845,
    date: "2020-09-19",
    image1: "src/public/images/CLIMATISEUR 1.jpeg",
    image2: "src/public/images/CLIMATISEUR 2.jpeg",
  },
  {
    id: 5,
    name: "Hommes",
    category: "Vêtements",
    title: "T-shirt Basique",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 1500,
    date: "2020-05-06",
    image1: "src/public/images/homme3.jpeg",
    image2: "src/public/images/homme4.jpeg",
  },
  {
    id: 6,
    name: "Parfums",
    category: "Cosmétiques",
    title: "Parfum Homme Boss",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 300,
    date: "2020-02-01",
    image1: "src/public/images/boss1.jpeg",
    image2: "src/public/images/boss2.jpeg",
  },
  {
    id: 7,
    name: "Machine à laver",
    category: "Électroménagers",
    title: "Lave-linge Automatique",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 1562,
    date: "2024-03-19",
    image1: "src/public/images/laverie1.jpeg",
    image2: "src/public/images/laverie1.jpeg",
  },
  {
    id: 8,
    name: "Bureaux",
    category: "Meubles",
    title: "Bureau de Travail",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 1522,
    date: "2021-12-17",
    image1: "src/public/images/bureau1.jpeg",
    image2: "src/public/images/bureau2.jpeg",
  },
  {
    id: 9,
    name: "Gommages",
    category: "Cosmétiques",
    title: "Gommage Naturel",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 3567,
    date: "2023-08-12",
    image1: "src/public/images/gommage1.jpeg",
    image2: "src/public/images/gommage2.jpeg",
  },
  {
    id: 10,
    name: "Télévision",
    category: "Électroniques",
    title: "TV LG 50 pouces",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 4500,
    date: "2025-02-21",
    image1: "src/public/images/lg1.jpeg",
    image2: "src/public/images/lg2.jpeg",
  },
  {
    id: 11,
    name: "Réfrigérateurs",
    category: "Électroménagers",
    title: "Frigo Double Porte",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 2000,
    date: "2022-06-14",
    image1: "src/public/images/laverie3.jpeg",
    image2: "src/public/images/laverie4.jpeg",
  },
  {
    id: 12,
    name: "Lits et Matelas",
    category: "Meubles",
    title: "Lit 2 Places",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 1500,
    date: "2021-12-28",
    image1: "src/public/images/lit1.jpeg",
    image2: "src/public/images/lit2.jpeg",
  },
  {
    id: 13,
    name: "Téléphone",
    category: "Électroniques",
    title: "Google Pixel",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 1000,
    date: "2021-12-01",
    image1: "src/public/images/pixel1.jpeg",
    image2: "src/public/images/pixel2.jpeg",
  },
  {
    id: 14,
    name: "Savons",
    category: "Cosmétiques",
    title: "Savon Bio",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 567,
    date: "2021-08-13",
    image1: "src/public/images/savon3.jpeg",
    image2: "src/public/images/savon4.jpeg",
  },
  {
    id: 15,
    name: "Fers à repasser",
    category: "Électroménagers",
    title: "Fer Vapeur",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 600,
    date: "2023-05-08",
    image1: "src/public/images/iron5.jpeg",
    image2: "src/public/images/iron6.jpeg",
  },
  {
    id: 16,
    name: "Micro-ondes",
    category: "Électroménagers",
    title: "Micro-ondes Numérique",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 250,
    date: "2023-10-01",
    image1: "src/public/images/cuisine1.jpeg",
    image2: "src/public/images/cuisine2.jpeg",
  },
  {
    id: 17,
    name: "Salles à manger",
    category: "Meubles",
    title: "Table Salle à Manger",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 800,
    date: "2025-07-01",
    image1: "src/public/images/salle1.jpeg",
    image2: "src/public/images/salle2.jpeg",
  },
  {
    id: 18,
    name: "Ensemble Bébé",
    category: "Vêtements",
    title: "Vêtements Bébé",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 60,
    date: "2022-05-01",
    image1: "src/public/images/enfant1.jpeg",
    image2: "src/public/images/enfant2.jpeg",
  },
  {
    id: 19,
    name: "Samsung Ultra",
    category: "Électroniques",
    title: "Samsung S23 Ultra",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 50,
    date: "2025-05-11",
    image1: "src/public/images/office3.jpeg",
    image2: "src/public/images/office4.jpeg",
  },
  {
    id: 20,
    name: "Robe",
    category: "Vêtements",
    title: "Robe Élégante",
    price: 60,
    oldPrice: 70.90,
    discount: 10.90,
    reviews: 500,
    date: "2024-04-15",
    image1: "src/public/images/femme2.jpeg",
    image2: "src/public/images/femme3.jpeg",
  },
];
